//------------------------------------------------------------------------
// Copyright(c) 2024 ARKSYN Audio.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename "ARKGain.vst3"
#if SMTG_PLATFORM_64
    #define stringFileDescription "ARKGain VST3 (64Bit)"
#else
    #define stringFileDescription "ARKGain VST3"
#endif
#define stringCompanyName "ARKSYN Audio\0"
#define stringLegalCopyright "Copyright(c) 2024 ARKSYN Audio."
#define stringLegalTrademarks "VST is a trademark of Steinberg Media Technologies GmbH"
